const h3 = {
  fontSize: "1rem",
  marginTop: 24,
  marginBottom: 8,
  color: "#d4a853",
  fontFamily: "Georgia, serif",
} as const;

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 32 }}>
      <h2 style={{ fontSize: "1.25rem", marginBottom: 10, color: "#d4a853", fontFamily: "Georgia, serif" }}>{title}</h2>
      {children}
    </section>
  );
}

export default function PrivacyPage() {
  return (
    <main
      style={{
        maxWidth: 800,
        margin: "0 auto",
        padding: "40px 24px",
        fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        color: "#e2d5c3",
        lineHeight: 1.8,
        background: "#0a0a0f",
        minHeight: "100vh",
      }}
    >
      <h1 style={{ fontSize: "2rem", marginBottom: 4, color: "#d4a853", fontFamily: "Georgia, serif" }}>Privacy Policy</h1>
      <p style={{ color: "#6b5a44", marginBottom: 40 }}>After Dark Tales — Last updated: April 2026</p>

      <div style={{ display: "flex", flexDirection: "column", gap: 12, marginBottom: 40 }}>
        <div style={{ background: "rgba(212,168,83,0.06)", border: "1px solid rgba(212,168,83,0.3)", borderRadius: 12, padding: "16px 20px" }}>
          <p style={{ margin: 0, fontWeight: 600, color: "#d4a853" }}>We keep data collection to a minimum.</p>
          <p style={{ margin: "6px 0 0", color: "#8b7355", fontSize: "0.9rem" }}>
            Profile names, profile images, reading counters, and age-verification status are stored on your device.
          </p>
        </div>

        <div style={{ background: "rgba(167,139,250,0.06)", border: "1px solid rgba(167,139,250,0.25)", borderRadius: 12, padding: "16px 20px" }}>
          <p style={{ margin: 0, fontWeight: 600, color: "#a78bfa" }}>Stories are generated by AI in response to your request.</p>
          <p style={{ margin: "6px 0 0", color: "#8b7355", fontSize: "0.9rem" }}>
            When you request a story, the genre, tone, length, and story notes you provide are sent to our AI provider for generation.
          </p>
        </div>

        <div style={{ background: "rgba(248,113,113,0.06)", border: "1px solid rgba(248,113,113,0.25)", borderRadius: 12, padding: "16px 20px" }}>
          <p style={{ margin: 0, fontWeight: 600, color: "#f87171" }}>After Dark Tales is intended for adults aged 18 and over.</p>
          <p style={{ margin: "6px 0 0", color: "#8b7355", fontSize: "0.9rem" }}>
            A local age-verification check is used to confirm eligibility on this device.
          </p>
        </div>
      </div>

      <Section title="1. Our Approach to Privacy">
        <p>
          After Dark Tales is designed to minimise the information we collect and store. Most app data stays on your device, and we use third-party services only where needed to provide story generation and app hosting.
        </p>
        <p>
          We do not sell your information, and we do not use your profile details for advertising.
        </p>
      </Section>

      <Section title="2. Who This Service Is For">
        <p>
          After Dark Tales is intended only for adults aged 18 and over. If a user cannot confirm that they are an adult, access should not be granted.
        </p>
      </Section>

      <Section title="3. Age Verification">
        <p>
          On first use, you are asked to confirm that you are 18 or over. This check is used to control access to the app on your device.
        </p>
        <p>
          A local verification flag may be stored on your device so you do not need to repeat the check each time.
        </p>
      </Section>

      <Section title="4. AI-Generated Content">
        <p>
          All stories in After Dark Tales are generated by AI. Stories are created based on the genre, tone, length, and story notes you provide.
        </p>

        <h3 style={h3}>Content safeguards</h3>
        <p>
          We use automated safeguards intended to block prohibited requests, including content involving minors, non-consensual sexual content, bestiality, incest, necrophilia, and certain violent or hateful material.
        </p>

        <h3 style={h3}>Reporting</h3>
        <p>
          If generated content appears to break our content rules, you can use the in-app reporting feature so that we can improve our safeguards.
        </p>
      </Section>

      <Section title="5. Information Used by the App">
        <h3 style={h3}>Stored on your device</h3>
        <p>
          Profile names, profile images, usage counters, credit balances, and age-verification status may be stored locally on your device.
        </p>

        <h3 style={h3}>Story requests</h3>
        <p>
          When you request a story, the genre, style, length, and any story notes you provide are sent to our AI provider for the purpose of generating content.
        </p>

        <h3 style={h3}>Technical service data</h3>
        <p>
          Our hosting provider may process standard technical request data, such as IP address, timestamps, and device-related information, for security, reliability, and performance.
        </p>
      </Section>

      <Section title="6. Third-Party Services">
        <p>
          After Dark Tales may rely on third-party providers such as an AI API provider and a hosting platform. Those providers may process data as needed to deliver their services.
        </p>
        <p>
          Please avoid entering sensitive personal information into story prompts.
        </p>
      </Section>

      <Section title="7. Children">
        <p>
          This service is not intended for children. It should not be used by anyone under 18.
        </p>
      </Section>

      <Section title="8. Changes to This Policy">
        <p>
          We may update this policy from time to time. If we make material changes, we will update the effective date shown at the top of this page.
        </p>
      </Section>

      <Section title="9. Plain Language Summary">
        <p>
          After Dark Tales stores most app information on your device. Story requests are sent to an AI provider so stories can be generated. A hosting provider may process standard technical logs to keep the service running. The service is intended for adults aged 18 and over.
        </p>
      </Section>
    </main>
  );
}
